# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: self-destruct
          POSTGRES_DB: self-destruct-test
          POSTGRES_PASSWORD: ""

    working_directory: ~/self-destruct

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run:
          name: run leiningen tests
          environment:
            DATABASE_URL: "jdbc:postgresql://self-destruct:@localhost:5432/self-destruct-test"
          command: lein test

  # deploy-prod:
  #   working_directory: ~/self-destruct
  #   docker:
  #     - image: circleci/clojure:lein-2.9.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: setup heroku
  #         command: bash .circleci/setup-heroku.sh
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "7e:f6:06:60:8b:d5:b3:e9:76:d7:9a:1f:fd:c4:d2:aa"


# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy-prod:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
